accelerator:  gpu
devices: 1
max_epochs: 10
log_every_n_steps: 10
deterministic: true
limit_train_batches: 0.25
limit_val_batches: ${trainer.limit_train_batches}

# WandB Logger
project: MLOpsPractice
entity: vanthoff007-indian-institute-of-technology-madras
name: BERT_Train_2