name: mlops
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py313hd6074c6_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py313h18e8e13_0
  - brotli-python=1.2.0=py313hf159716_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.13.11=py313hd8ed1ab_100
  - cuda-crt-tools=12.9.86=ha770c72_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hffce074_1
  - cuda-cupti=12.9.79=h676940d_1
  - cuda-nvcc-tools=12.9.86=he02047a_2
  - cuda-nvdisasm=12.9.88=hffce074_1
  - cuda-nvrtc=12.9.86=hecca717_1
  - cuda-nvtx=12.9.79=hecca717_1
  - cuda-nvvm-tools=12.9.86=h4bc722e_2
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.2.21=hbcb9cd8_0
  - filelock=3.20.3=pyhd8ed1ab_0
  - fmt=12.1.0=hff5e90c_0
  - frozenlist=1.7.0=py313h6b9daa2_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py313h86d8783_2
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libabseil=20250512.1=cxx17_hba17884_0
  - libblas=3.11.0=5_h5875eb1_mkl
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_hfef963f_mkl
  - libcublas=12.9.1.4=h676940d_1
  - libcudnn=9.10.2.21=hf7e9902_0
  - libcudnn-dev=9.10.2.21=h58dd1b1_0
  - libcudss=0.7.1.4=h58dd1b1_0
  - libcufft=11.4.1.4=hecca717_1
  - libcufile=1.14.1.1=hbc026e6_1
  - libcurand=10.3.10.19=h676940d_1
  - libcusolver=11.7.5.82=h676940d_2
  - libcusparse=12.5.10.65=hecca717_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - liblapack=3.11.0=5_h5e43f62_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - libmagma=2.9.0=ha7672b3_6
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnvjitlink=12.9.86=hecca717_2
  - libprotobuf=6.31.1=h49aed37_4
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsystemd0=258.3=h6569c3e_0
  - libtorch=2.9.1=cuda129_mkl_hf5f578d_303
  - libudev1=258.3=h6569c3e_0
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning=2.6.0=pyhcf101f3_0
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvm-openmp=21.1.8=h4922eb0_0
  - markupsafe=3.0.3=py313h3dea7bd_0
  - mkl=2025.3.0=h0e700b2_463
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.7.0=py313h3dea7bd_0
  - nccl=2.29.2.1=h4d09622_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.6.1=pyhcf101f3_0
  - numpy=2.4.1=py313hf6604e3_0
  - openssl=3.6.0=h26f9b46_0
  - optree=0.18.0=py313h7037e92_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.3=pyh145f28c_0
  - propcache=0.3.1=py313h8060acc_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-abi=11=hc364b38_1
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.11=hc97d973_100_cp313
  - python_abi=3.13=8_cp313
  - pytorch=2.9.1=cuda129_mkl_py313_h9830416_303
  - pytorch-lightning=2.6.0=pyhcf101f3_0
  - pyyaml=6.0.3=py313h3dea7bd_0
  - rdma-core=60.0=hecca717_0
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - setuptools=80.9.0=pyhff2d567_0
  - sleef=3.9.0=ha0421bc_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=hb700be7_2
  - tk=8.6.13=noxft_ha0e22de_103
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - triton=3.5.1=cuda129py313h246eb7c_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py313h3dea7bd_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - aiohttp-retry==2.9.1
      - amqp==5.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - appdirs==1.4.4
      - asyncssh==2.22.0
      - atpublic==7.0.0
      - billiard==4.2.4
      - celery==5.6.2
      - cffi==2.0.0
      - click==8.3.1
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1.2
      - click-repl==0.3.0
      - coloredlogs==15.0.1
      - configobj==5.0.9
      - cryptography==43.0.3
      - datasets==4.5.0
      - dictdiffer==0.9.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dpath==2.2.0
      - dulwich==1.0.0
      - dvc==3.66.1
      - dvc-data==3.18.2
      - dvc-gdrive==3.0.1
      - dvc-http==2.32.0
      - dvc-objects==5.2.0
      - dvc-render==1.0.2
      - dvc-studio-client==0.22.0
      - dvc-task==0.40.2
      - entrypoints==0.4
      - flatbuffers==25.12.19
      - flatten-dict==0.4.2
      - flufl-lock==9.0.0
      - fsspec==2025.10.0
      - funcy==2.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-api-core==2.29.0
      - google-api-python-client==2.188.0
      - google-auth==2.47.0
      - google-auth-httplib2==0.3.0
      - googleapis-common-protos==1.72.0
      - grandalf==0.8
      - grpcio==1.76.0
      - gto==1.9.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - iterative-telemetry==0.0.10
      - kombu==5.6.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - multiprocess==0.70.18
      - oauth2client==4.1.3
      - omegaconf==2.3.0
      - onnx==1.20.1
      - onnx-ir==0.1.15
      - onnxruntime==1.23.2
      - onnxscript==0.5.7
      - orjson==3.11.5
      - pandas==2.3.3
      - pathspec==0.12.1
      - pillow==12.1.0
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - proto-plus==1.27.0
      - protobuf==6.33.4
      - psutil==7.2.1
      - pyarrow==22.0.0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydot==4.0.1
      - pydrive2==1.21.3
      - pygit2==1.19.1
      - pygments==2.19.2
      - pygtrie==2.5.0
      - pyopenssl==24.2.1
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - regex==2026.1.15
      - rich==14.2.0
      - rsa==4.9.1
      - ruamel-yaml==0.19.1
      - safetensors==0.7.0
      - scipy==1.17.0
      - scmrepo==3.6.1
      - semver==3.0.4
      - sentry-sdk==2.49.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.8.0
      - six==1.17.0
      - smmap==5.0.2
      - sqltrie==0.11.2
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tokenizers==0.22.2
      - tomlkit==0.14.0
      - transformers==4.57.5
      - typer==0.21.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - tzlocal==5.3.1
      - uritemplate==4.2.0
      - vine==5.1.0
      - voluptuous==0.16.0
      - wandb==0.24.0
      - wcwidth==0.2.14
      - werkzeug==3.1.5
      - xxhash==3.6.0
      - zc-lockfile==4.0
prefix: /home/arjav.singh/miniconda3/envs/mlops
